#### Prepared for Gabor's Data Analysis

### Data Analysis for Business, Economics, and Policy
by Gabor Bekes and  Gabor Kezdi
 
Cambridge University Press 2021

**[gabors-data-analysis.com ](https://gabors-data-analysis.com/)**

 License: Free to share, modify and use for educational purposes. 
 Not to be used for commercial purposes.

### Chapter 01
**CH01A Finding a Good Deal among Hotels: Data Collection**

hotels-vienna dataset

version 0.9.0 2025-08-14

### Chapter 01
#### First look at the hotels data

In [1]:
import os
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

In [2]:
# Current script folder
current_path = os.getcwd()
dirname = current_path.split("da_case_studies")[0]

# location folders
data_in = dirname + "da_data_repo/hotels-vienna/clean/"
data_out = dirname + "da_case_studies/ch01-hotels-data-collect/"
output = dirname + "da_case_studies/ch01-hotels-data-collect/output/"
func = dirname + "da_case_studies/ch00-tech-prep/"
sys.path.append(func)

In [3]:
# Import the prewritten helper functions 
from da_helper_functions import *

In [4]:
# load in clean and tidy data and create workfile
df = pd.read_csv(data_in + "hotels-vienna.csv")

# Download directly if you did not set up the folders
#df = pd.read_csv("https://osf.io/y6jvb/download")

In [5]:
############################################
# First look
############################################
df = df.filter(
    [
        "hotel_id",
        "accommodation_type",
        "country",
        "city",
        "city_actual",
        "neighbourhood",
        "center1label",
        "distance",
        "center2label",
        "distance_alter",
        "stars",
        "rating",
        "rating_count",
        "ratingta",
        "ratingta_count",
        "year",
        "month",
        "weekend",
        "holiday",
        "nnights",
        "price",
        "scarce_room",
        "offer",
        "offer_cat",
    ]
)

In [6]:
df.describe()

,hotel_id,distance,distance_alter,stars,rating,rating_count,ratingta,ratingta_count,year,month,weekend,holiday,nnights,price,scarce_room,offer
count,428.000000,428.000000,428.000000,428.000000,393.000000,393.000000,325.000000,325.000000,428.0,428.0,428.0,428.0,428.0,428.000000,428.000000,428.000000
mean,22153.502336,1.658879,3.718458,3.434579,3.970992,155.048346,3.990769,556.516923,2017.0,11.0,0.0,0.0,1.0,131.366822,0.598131,0.679907
std,146.858477,1.595673,1.631341,0.772278,0.577444,191.217435,0.482638,586.874582,0.0,0.0,0.0,0.0,0.0,91.580545,0.490850,0.467058
min,21894.000000,0.000000,0.600000,1.000000,1.000000,1.000000,2.000000,2.000000,2017.0,11.0,0.0,0.0,1.0,27.000000,0.000000,0.000000
25%,22027.750000,0.700000,2.700000,3.000000,3.700000,27.000000,3.500000,129.000000,2017.0,11.0,0.0,0.0,1.0,83.000000,0.000000,0.000000
50%,22155.500000,1.300000,3.400000,3.500000,4.000000,84.000000,4.000000,335.000000,2017.0,11.0,0.0,0.0,1.0,109.500000,1.000000,1.000000
75%,22279.250000,2.000000,4.400000,4.000000,4.400000,203.000000,4.500000,811.000000,2017.0,11.0,0.0,0.0,1.0,146.000000,1.000000,1.000000
max,22409.000000,13.000000,13.000000,5.000000,5.000000,1541.000000,5.000000,3171.000000,2017.0,11.0,0.0,0.0,1.0,1012.000000,1.000000,1.000000

In [7]:
df = df.filter(
    [
        "hotel_id",
        "accommodation_type",
        "country",
        "city",
        "city_actual",
        "center1label",
        "distance",
        "stars",
        "rating",
        "price",
    ]
)

### Table 1.1

In [8]:
df.head()

,hotel_id,accommodation_type,country,city,city_actual,center1label,distance,stars,rating,price
0,21894,Apartment,Austria,Vienna,Vienna,City centre,2.7,4.0,4.4,81
1,21897,Hotel,Austria,Vienna,Vienna,City centre,1.7,4.0,3.9,81
2,21901,Hotel,Austria,Vienna,Vienna,City centre,1.4,4.0,3.7,85
3,21902,Hotel,Austria,Vienna,Vienna,City centre,1.7,3.0,4.0,83
4,21903,Hotel,Austria,Vienna,Vienna,City centre,1.2,4.0,3.9,82

In [10]:
os.mkdir(output)
df.loc[0:4].to_csv(output + "hotel_listobs.csv", index=False)

In [11]:
df.columns

Index(['hotel_id', 'accommodation_type', 'country', 'city', 'city_actual',
       'center1label', 'distance', 'stars', 'rating', 'price'],
      dtype='object')

In [12]:
df["price"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 428 entries, 0 to 427
Series name: price
Non-Null Count  Dtype
--------------  -----
428 non-null    int64
dtypes: int64(1)
memory usage: 3.5 KB

In [13]:
df["price"].isna().sum()

0

In [16]:
# Selecionar os preços válidos
precos = df["price"].dropna()

# Média de todos os hotéis
media_completa = precos.mean()

# Tamanhos solicitados pelo exercício
tamanhos = [25, 50, 200]

# Lista que receberá os resultados
resultados = []

# Repetir o exercício três vezes
for repeticao in range(1, 4):

    for tamanho in tamanhos:

        amostra = precos.sample(
            n=tamanho,
            replace=False,
            random_state=repeticao
        )

        media_amostra = amostra.mean()

        resultados.append({
            "repeticao": repeticao,
            "tamanho_amostra": tamanho,
            "media_amostra": media_amostra,
            "media_completa": media_completa,
            "diferenca": media_amostra - media_completa
        })

# Transformar os resultados em uma tabela
resultados_df = pd.DataFrame(resultados)

# Arredondar para duas casas decimais
resultados_df = resultados_df.round(2)

resultados_df

   repeticao  tamanho_amostra  media_amostra  media_completa  diferenca
0          1               25         124.36          131.37      -7.01
1          1               50         142.74          131.37      11.37
2          1              200         132.79          131.37       1.42
3          2               25         143.32          131.37      11.95
4          2               50         137.28          131.37       5.91
5          2              200         132.25          131.37       0.88
6          3               25         112.96          131.37     -18.41
7          3               50         132.56          131.37       1.19
8          3              200         130.82          131.37      -0.55

In [18]:
print(f"Média da base completa: {media_completa:.2f}")

tabela_medias

Média da base completa: 131.37

tamanho_amostra     25      50      200
repeticao
1                124.36  142.74  132.79
2                143.32  137.28  132.25
3                112.96  132.56  130.82